### PR TITLE
removed code that is being overwritten to avoid confusion

### PR DESCRIPTION
**Pull request by bdwyer2**
Removed unused code to avoid confusion

### CODE REVIEW

**Comment by ptitzler** [comment]
Make sure to forward-fit all enhancements that might be present in these files but are not included in the skeleton.

**Comment by bdwyer2** [comment]
@ptitzler the only thing added to this was the CORS support

**Review by ajbozarth — APPROVED** [review]
As long as we move the CORS support to the skeleton/new framework as pointed out by Patrick this LGTM

**Comment by ptitzler** [comment]
Issue is already open https://github.ibm.com/CODAIT/MAX-skeleton/issues/18

**Review by djalova — APPROVED** [review]

**Pull request merged**
