### PR TITLE
Upgrade base image to continuumio/miniconda3:4.7.12

### PR DESCRIPTION
**Pull request by xuhdev**
The latest image uses Python 3.7: https://github.com/ContinuumIO/docker-images/tree/master/miniconda3

### CODE REVIEW

**Review by bdwyer2 — APPROVED** [review]
Should we cut a new release once this is merged in?

**Comment by xuhdev** [comment]
Yeah I think so. We probably want all models to test out this new base.

**Comment by xuhdev** [comment]
Should we cut a new release now?

**Comment by bdwyer2** [comment]
@xuhdev sure

**Comment by xuhdev** [comment]
Could you help? No idea of the process

**Comment by bdwyer2** [comment]
Done https://github.com/IBM/MAX-Base/releases/tag/v1.3.0

**Comment by xuhdev** [comment]
Like a flash

**Pull request merged**
