### PR TITLE
Update maxfw version to v1.1.0

### PR DESCRIPTION
**Pull request by ajbozarth**
https://github.com/IBM/MAX-Framework/pull/10 includes a version update to v1.1.0 to support the Object Detector. Once that version update is approved and released this should be merged to propagate the changes to the models

### CODE REVIEW

**Review by bdwyer2 — APPROVED** [review]
Let's wait for `maxfw` `1.1.0` to be released on pypi before merging this

**Comment by ajbozarth** [comment]
@bdwyer2 that was my intent, just wanted this open since https://github.com/IBM/MAX-Object-Detector/pull/39 depends on it

**Comment by ajbozarth** [comment]
Also travis will fail until the update is on pypi anyway

**Comment by ajbozarth** [comment]
pypi is updated and builds pass, merging

**Pull request merged**
